name: Angular Build and Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.1'

      - name : Install Angular
        run: npm install -g @angular/cli@15

      - name: Install Angular CDK
        run: npm i @angular/cdk -f

      - name: Install dependencies
        run: npm install -f

      - name: Build Angular project
        run: ng build

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and Run Docker containers
        run: |
          docker-compose -f ./docker-compose.yml up -d
